baseURL = 'https://pollytechnically.com/'
languageCode = 'en-uk'
title = 'Polly, Technically'
theme = 'anatole'

[params]
title = "Polly, Technically"
author = "Polina Zaichkina"
description = """
Thoughts, tips, and woes
London's best* tech writer
"""
profilePicture = "images/polly-logo.png"
ogImage = "/images/polly-logo.png"
socialShareImage = "/images/polly-logo.png"
displayMode = "light"
disableThemeSwitcher = true
contentratio = 0.7
reversepagetitle = true
enableOpenGraph = true
disableTitleCapitalization = true
disableArchiveTitleStyling = true
